### ISSUE TITLE
Would probably fail in bundle environment

### ISSUE THREAD

**Issue by mubaidr** [flexdinesh/browser-or-node#1]
I think Bundlers (like webpack, parcel) define these properties/methods n their own, so i think this will fail in those environments. 

```js
const isNode = typeof module !== 'undefined' && typeof module.exports !== 'undefined';
```

**Comment by swansontec** [comment]
I can confirm that this fails with the [Parcel](https://parceljs.org/) bundler. I get `isNode === true`, even in the browser.

**Comment by swansontec** [comment]
https://github.com/flexdinesh/browser-or-node/pull/2

**Comment by flexdinesh** [comment]
PR #2 should address this issue. Closing it as it's been merged.

**Comment by cesarve77** [comment]
It still fail with babelify browserify
IsNode===true

**Comment by flexdinesh** [comment]
@cesarve77 I haven't published a new version yet. I'll definitely publish a new version tomorrow.

**Comment by flexdinesh** [comment]
v1.1.0 is now published with these changes.
