### ISSUE TITLE
deno

### ISSUE THREAD

**Issue by audiolion** [flexdinesh/browser-or-node#14]
probably out of the scope of this package due to the name, but it would be cool to have an isDeno check as well.

**Comment by Onyxzen** [comment]
Hello there, I know it's a bit late (because I only stumbled across this repository a few minutes ago. I've submitted a PR for the requested `isDeno` [here](https://github.com/flexdinesh/browser-or-node/pull/19). Let me know if there's any issues on Deno regarding this.

**Comment by flexdinesh** [comment]
`isDeno` support released with version `v2.0.0`.

https://github.com/flexdinesh/browser-or-node/releases/tag/v2.0.0
